concurrent = 4
check_interval = 3
log_level = "info"
log_format = "runner"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "example-docker-runner"
  url = "https://gitlab.example.com"
  token = "example-token-123"
  executor = "docker"
  limit = 2
  output_limit = 4096
  request_concurrency = 1
  
  [runners.docker]
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0

[[runners]]
  name = "example-shell-runner"
  url = "https://gitlab.example.com" 
  token = "example-token-456"
  executor = "shell"
  shell = "bash"
  limit = 1